<a href="https://colab.research.google.com/github/Ritesh-panda/NLP-Learnings/blob/main/TF_IDF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [12]:
df=pd.read_csv("/content/Ecommerce_data.csv", engine='python', on_bad_lines='skip')

In [13]:
df.head()

                                                Text                   label
0  Urban Ladder Eisner Low Back Study-Office Comp...               Household
1  Contrast living Wooden Decorative Box,Painted ...               Household
2  IO Crest SY-PCI40010 PCI RAID Host Controller ...             Electronics
3  ISAKAA Baby Socks from Just Born to 8 Years- P...  Clothing & Accessories
4  Indira Designer Women's Art Mysore Silk Saree ...  Clothing & Accessories

In [16]:
df.label.value_counts()

label
Household                 6000
Electronics               6000
Clothing & Accessories    6000
Books                     6000
Name: count, dtype: int64

In [3]:
corpus=[
    "Thor eating pizza, loki is eating pizza, ironman ate pizza already",
"google is announcing new pixel 6 tomorrow",
"apple is announcing new iphone tomorrow",
"microsoft is announcing new surface tomorrow",
"tesla is announcing new model 3 tomorrow",
"amazon is announcing new echo-dot tomorrow"
"i am eating biriyani and you are eating grapes"]

In [4]:
v=TfidfVectorizer()
v.fit(corpus)
transform_output=v.transform(corpus)

In [5]:
print(v.vocabulary_)

{'thor': 25, 'eating': 10, 'pizza': 22, 'loki': 17, 'is': 16, 'ironman': 15, 'ate': 7, 'already': 0, 'google': 12, 'announcing': 4, 'new': 20, 'pixel': 21, 'tomorrow': 26, 'apple': 5, 'iphone': 14, 'microsoft': 18, 'surface': 23, 'tesla': 24, 'model': 19, 'amazon': 2, 'echo': 11, 'dot': 9, 'tomorrowi': 27, 'am': 1, 'biriyani': 8, 'and': 3, 'you': 28, 'are': 6, 'grapes': 13}

In [6]:
#print idf for each word
all_feature_names=v.get_feature_names_out()
for word in all_feature_names:
  indx=v.vocabulary_.get(word)
  idf_score=v.idf_[indx]
  print(f"{word}:{idf_score}")

already:2.252762968495368
am:2.252762968495368
amazon:2.252762968495368
and:2.252762968495368
announcing:1.1541506798272583
apple:2.252762968495368
are:2.252762968495368
ate:2.252762968495368
biriyani:2.252762968495368
dot:2.252762968495368
eating:1.8472978603872037
echo:2.252762968495368
google:2.252762968495368
grapes:2.252762968495368
iphone:2.252762968495368
ironman:2.252762968495368
is:1.0
loki:2.252762968495368
microsoft:2.252762968495368
model:2.252762968495368
new:1.1541506798272583
pixel:2.252762968495368
pizza:2.252762968495368
surface:2.252762968495368
tesla:2.252762968495368
thor:2.252762968495368
tomorrow:1.336472236621213
tomorrowi:2.252762968495368
you:2.252762968495368

In [17]:
df['label_num'] = df['label'].map({
    'Household':0,
'Electronics':1	,
'Clothing & Accessories':2	,
'Books':3
})

In [20]:
#train test spilt
X_train,X_test,y_train,y_test=train_test_split(df.Text,df.label_num,test_size=0.2 , random_state=42)

###Vectorizer

In [25]:
v1=TfidfVectorizer()
x_train_tf=v1.fit_transform(X_train)
x_test_tf=v1.transform(X_test)

###classification model

In [21]:
from sklearn.tree import DecisionTreeClassifier

In [27]:
model=DecisionTreeClassifier()
model.fit(x_train_tf,y_train)
model.predict(x_test_tf)
model.score(x_test_tf,y_test)

0.9464583333333333

In [30]:
print(classification_report(y_test,model.predict(x_test_tf)))

              precision    recall  f1-score   support

           0       0.92      0.92      0.92      1221
           1       0.95      0.95      0.95      1145
           2       0.97      0.95      0.96      1210
           3       0.95      0.96      0.96      1224

    accuracy                           0.95      4800
   macro avg       0.95      0.95      0.95      4800
weighted avg       0.95      0.95      0.95      4800